### ISSUE TITLE
I wanna use X.509 Certificate Mode at lwm2m server after bootstraping with X.509 Certificate Mode

### ISSUE THREAD

**Issue by huny0501** [eclipse-leshan/leshan#1458]
### Question

I wanna use X.509 Certificate Mode at lwm2m server after bootstraping with X.509 Certificate Mode

I wanna use X.509 Certificate Mode at both server.

But I have to add information of client private key and public key at bootstrap server for using X.509 certificate Mode at lwm2m server.

But bootstrap server can not know certification information fo client.

how can i use?

**Comment by huny0501** [comment]
they have private key , public key each other (client, bootstrap server, lwm2m server)

**Comment by sbernard31** [comment]
I'm not sure I get your point, Just to be sure I try to rephrase it. 

You want to use X509 for connection between : 
 - LWM2M Client and LWM2M Bootstrap Server.
 - LWM2M Client and LWM2M Server. 

I guess you are  using Leshan Demos ? right ?
 
 > But I have to add information of client private key and public key at bootstrap server for using X.509 certificate Mode at lwm2m server.
 
 You mean that **leshan-bsserver-demo** required you to provide Client Certificate and Client Private Key when you add you Client configuration via `Add Client Configuration` wizzard of the UI ? right ? 
 
 > But bootstrap server can not know certification information fo client.
 
 You mean in your use case,  you don't want to provide those information to Bootstrap Server (I guess maybe for some kind of  Security reason), right ? 
 
 Do I correctly understand you ?

**Comment by huny0501** [comment]
Like when Client connect lwm2m server directly with X.509 Mode without bootstrap session

**Comment by huny0501** [comment]
to use X.509 Mode in lwm2m server, I have to add client certificate information in bootsrap server UI
But I cannot know Client Private Key in real service, so I cannot add Client Certificate Information and Security Mode (In 4. LWM2M Server Configuration)
I had no choice so I add Client Information in 4.LWM2M Server Configuration as below
> Server URL : coaps://localhost:5684
Sevutiry Mode : No Security

However, the lwm2m server did not respond. it is issue..

It is my client option
> -b
-u=localhost:5694
-n=test
-ccert=D:\client_sign.der
-cprik=D:\client_private_pkcs8.der
-scert=D:\server_sign.der


if you need to get more information, plz ask me
thank you for your help.

**Comment by sbernard31** [comment]
For sure : 
> Server URL : coaps://localhost:5684
> Sevutiry Mode : No Security

This can not work. because **No Security** is for `coap://`  (not  for `coaps://`).

> But I cannot know Client Private Key in real service, so I cannot add Client Certificate Information and Security Mode (In 4. LWM2M Server Configuration)

The idea is not to provide the client private key already store in the client but providing a new Private Key / Certificate Pair which will only be used to connect to LWM2M Server Configuration. 

To be clearer, and looking at : 
 ```
    (1) Endpoint Name : Test
    (2) Credentials : Using (D)TLS ON
        Sevurity Mode ; x509
    (3) Paths to delete : /0, /1, /21
    (4) LWM2M Server Configuration : 
        Server URL : coaps://localhost:5684
        Sevutiry Mode : No Security
    (6) LWM2M Bootstrap Server Configuration : N/A
```
Step 2 is about "How Bootstrap server expects client to authenticate ?"
Step 4 is about "Apply Configuration which defines which LWM2M server the client must connect to  and which credentials will be used for this server only".

So you don't need to know the Private Key, you need to provide a new one (with the corresponding new Certificate trusted by your LWM2M server). 

Regarding your question, maybe this could help you if you read again the [LWM2M specification v.1.1.x](https://github.com/eclipse/leshan/wiki/Lightweight-M2M-Specification#lightweight-m2m-v11x) to clarify your mind about this. 
At least chapter : 
- https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-3-0-5283-X509-Certificates
- https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#13-1-0-E1-LwM2M-Object-LwM2M-Security
- https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#13-2-0-E2-LwM2M-Object-LwM2M-Server

And probably also : 
- https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-0-61-Bootstrap-Interface
- https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-0-52-TLSDTLS-based-Security

**Comment by huny0501** [comment]
thank you for your help :)
