### ISSUE TITLE
Leshan supports only COAP ? Shall we use STOMP service supported devices with eclipse-leshan?

### ISSUE THREAD

**Issue by M0ulinamary** [eclipse-leshan/leshan#1465]
### Question

I am about to start learning the eclipse leshan with the STOMP service. Please guide where to start with

**Comment by sbernard31** [comment]
Oh there is also some more specific question in the title, I tried to answer.

> Leshan supports only COAP ?

**Leshan** aims to implement [**LWM2M specification**](https://github.com/eclipse-leshan/leshan/wiki/Lightweight-M2M-Specification).
**Leshan v1.x**  (current stable version) implements **LWM2M v1.0.x** which specifies only LWM2M over `coap(s)`
**Leshan v2.x** (in development version) implements **LWM2M v1.1.x** which specifies only LWM2M over : 
  - `coap(s)` currently implemented.
  - `coap+tcp(s)` for which there is some development started : https://github.com/eclipse-leshan/leshan/issues/1047 
  - `coap over NIDD` for which there is no development started. 

Since **Leshan v2.x**  a transport abstraction has been added to Leshan to be able to add you transport but this is pretty new and so probably improvable. See for more details :  https://github.com/eclipse-leshan/leshan/issues/1025#issuecomment-1373824399
  
**LWM2M v1.2.x** specifies LWM2M over : 
- `mqtt`
- `http` but it seems not really functional : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/520

but currently there is no version of **Leshan** which aims to implement **LWM2M v1.2.x**.

> Shall we use STOMP service supported devices with eclipse-leshan?

I'm not sure to understand the question.   
Are you talking about [STOMP](https://stomp.github.io/) ?  
I don't know any LWM2M specification which define STOMP as transport. If this exits please share the link.

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by sbernard31** [comment]
I close it but feel free to reopen if needed.

If you succeed to implement something using new Transport Layer Abstraction, please let us know. :pray:
