### ISSUE TITLE
where can I find the jar file or module that includes the server for clustering with Redis?

### ISSUE THREAD

**Issue by allaismail** [eclipse-leshan/leshan#1474]
### Question

Greetings everyone,

I'm in search of the jar file or module that houses the server required for Redis clustering. I intend to implement a server cluster and I specifically need the server that can broadcast response messages in channels like LESHAN_RESP and others. Can anyone guide me to the appropriate resource?

thank you

**Comment by sbernard31** [comment]
I guess you refer to an old Leshan module which aimed to provide a way to run Leshan in a cluster named **leshan-server-cluster**. 

This module was removed before the release of Leshan v1.0.0 and is not supported anymore.
AFAIK, there is no plan add this kind of feature again, (at least at short mid/term) because we are focus on core LWM2M feature.

You could have a look at :
 - https://github.com/eclipse-leshan/leshan/wiki/Using-Leshan-server-in-a-cluster
 - https://github.com/eclipse-leshan/leshan/wiki/Leshan-Cluster-Module

**Comment by allaismail** [comment]
Many thanks for your assistance!

Precisely, I extracted the content from version 1.0.0-M2 of the Leshan project in the Release section, and I built it using 'mvn' (Maven).
"leshan-server-cluster-1.0.0-M2-jar-with-dependencies.jar"

best.

**Comment by allaismail** [comment]
yes thank you

**Comment by sbernard31** [comment]
You're welcome
