### ISSUE TITLE
Is there a list of known Leshan vulnerabilities?

### ISSUE THREAD

**Issue by Warmek** [eclipse-leshan/leshan#1481]
### Question

Is there a list of known Leshan vulnerabilities or a plan to create such? If so, how to access it?

Also, we would be interested in setting up a process to inform Orange when a new security issue is discovered

**Comment by sbernard31** [comment]
> Is there a list of known Leshan vulnerabilities or a plan to create such?

You asked several time about security (#1449, #1439) and as you could guess with my previous answers all about security concerning Leshan is at [Security Policy](https://github.com/eclipse-leshan/leshan/security/policy).

Currently there is not known vulnerabilities in Leshan code directly.
I list all security issue caused by dependencies that I am aware of in Security Policy.  (I can not guarantee this is exhaustive)

>  If so, how to access it?

**Comment by sbernard31** [comment]
About disclosure, as indicated by Security Policy you could have a look at : 
 - https://www.eclipse.org/projects/handbook/#vulnerability-disclosure
 - https://www.eclipse.org/security/policy/

**Comment by mrybczyn** [comment]
@Warmek are you asking for a list of fixed issues? I think the list you're searching for is in: https://github.com/eclipse-leshan/leshan/blob/master/SECURITY.md

**Comment by Warmek** [comment]
>I'm not sure if you asked to be aware about vulnerability before it is public.
>If this is what you want I'm not sure this is a good practice. I could ask for help from Eclipse Security Team about that. 🤔

We would be thankful if you did

**Comment by mrybczyn** [comment]
> > I'm not sure if you asked to be aware about vulnerability before it is public.
> > If this is what you want I'm not sure this is a good practice. I could ask for help from Eclipse Security Team about that. 🤔
> 
> We would be thankful if you did

The Security Team is there. We are unsure what you're exactly asking about @Warmek . Known fixed vulnerabilities?

**Comment by mrybczyn** [comment]
Hello @Warmek, from my records:
- I see no direct fixed vulnerabilities in Leshan
- Indirect (in dependencies) are listed in https://github.com/eclipse-leshan/leshan/blob/master/SECURITY.md
- For active ones, we have none public. For information on non-public ones (so ones in the disclosure process), we won't post such information in a public place. The organization would need to have an extremely good reason to have such information. Also, so that you remember, we aim to make all security issues public. For more details on the Eclipse Foundation policy, you can check out https://www.eclipse.org/security/policy/

Hope that contains the information you need.

**Comment by sbernard31** [comment]
@Warmek  can we close this issue ?

**Comment by Warmek** [comment]
>For active ones, we have none public. For information on non-public ones (so ones in the disclosure process), we won't post such information in a public place. The organization would need to have an extremely good reason to have such information. Also, so that you remember, we aim to make all security issues public. For more details on the Eclipse Foundation policy, you can check out https://www.eclipse.org/security/policy/

The only reason would be to let us setting up a workaround on production directly on LiveObjects UNTIL a new Leshan Milestone is available.
But, as we have experienced last week with the “XXE Injection” issue, we saw that Leshan was very reactive and a Milestone M13 is already available to fix the issue. So we don't need, to be alerted in advance.
