### ISSUE TITLE
Leshan server demo seems to be down

### ISSUE THREAD

**Issue by tomekmalek** [eclipse-leshan/leshan#1501]
### Question

Hello,

Maybe it is known problem, but Leshan demo server (https://leshan.eclipseprojects.io/) answers: 503 Service Unavailable.

best regards
Tomasz

**Comment by sbernard31** [comment]
Oops I saw your message yesterday but forgot to look at this.

It seems you're right sandbox is down.

Looks like it is caused by exception in protocol stage thread: `Java heap space java.lang.OutOfMemoryError: Java heap space`

I restarted the sandbox, so it should work again. 

I also get a heap dump (.hprof) and I will try to look at it.

I will also see if we can configure the sandbox to crash on OutOfMemoryError, so it will be restarted by systemd  : https://stackoverflow.com/a/3878199/5088764

**Comment by sbernard31** [comment]
Thx for reporting this :pray:

**Comment by tomekmalek** [comment]
Now it is OK. Thx for action.

**Comment by sbernard31** [comment]
Most of memory usage is about coapendpoint worker in `ScheduledThreadPoolExecutor`. (~400 000 worker), without knowing what people do on the sandbox hard to say if this is "expected" behavior. 

sandbox demo are now started with options  `-XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError="kill -9 %p""
