### ISSUE TITLE
When I run mvn install the test fails. It's most likely an x509 issue.

### ISSUE THREAD

**Issue by malrancau** [eclipse-leshan/leshan#1509]
### Question

SecurityTest fails during testing step during mvn installation.

"Running org.eclipse.leshan.integration.tests.[1mSecurityTest"

Among the error phrases, 
"org.eclipse.leshan.integration.tests.SecurityTest.registered_device_with_x509cert_to_server_with_x509cert_rootca_certificate_usage_taa_intca_given(Protocol, String, String)[1]"' 
stands out.

I just read the README and ran mvn install normally from the root path of leshan-master.

Is there any way to fix this error?

This question was created using Google Translate.
Sorry if there is a problem with communication. I can not speak english well.

![image](https://github.com/eclipse-leshan/leshan/assets/50736807/de1df9c1-be03-48ec-bcb9-b3e73936845c)

**Comment by sbernard31** [comment]
I build Leshan almost every day and it is also built by github or jenkins without issue. (all run are on Linux)

So this is maybe a issue with your environment.  
Looking at https://github.com/eclipse-leshan/leshan/issues/1510, it seems you are using : 
 - maven 3.6.0
 -  java 17 (from Oracle)
 - Windows 10
 
 I'm not able to test in this environment.
 
 I understand you try to build `master` right ? (eventually share the exact commit id)
 
 > Is there any way to fix this error?
 
I don't know exactly what is the issue, but as a workaround you can skip the tests with : ` mvn clean install -DskipTests`
 
You tried to share the output of your build but : 
 1. you share image instead of text ... See why it's bad idea https://github.com/eclipse-leshan/leshan/issues/1510#issuecomment-1720864309 ...
 2. the output is not complete, please share the full log as text not image.

**Comment by malrancau** [comment]
@sbernard31 

Thanks for your reply.
Sorry for attaching an image.

Can I know sbernard31’s development environment?

I would like to try changing to Linux.

Please tell us your development environment, such as Maven, Java, or Linux.
We will proceed with reference to this.

**Comment by sbernard31** [comment]
> Can you tell me the development environment of sbernard31?

```
>> mvn --version  
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.20, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.10.0-23-amd64", arch: "amd64", family: "unix"
```
I also just tested with : `Java version: 17.0.7, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
 ` and it works for me too. 

But I"m on Debian 11 but I will probably upgrade to Debian 12 soon so it will change. 

Anyway, I guess this should work on Windows 10  too, so It would have been great to (at least) understand this issue ?  :thinking: 

Could you share full build output ?
And also if you could test : https://github.com/eclipse-leshan/leshan/issues/1461#issuecomment-1720873438, this could help ?
