### ISSUE TITLE
Java package is not created after 'mvn install' completes successfully.

### ISSUE THREAD

**Issue by malrancau** [eclipse-leshan/leshan#1510]
### Question

mvn install kept failing due to leshan test, so I commented out the test part in pom.xml and did mvn install.

The mvn install was successful, and a target folder was created in each folder such as bs, client, and server, and a .jar file was created.

However, there is no java package, perhaps because java is not compiled.

Is it because the leshan test was commented out in pom.xml?

I don't know why.

Images related to the issue are attached below.

![image](https://github.com/eclipse-leshan/leshan/assets/50736807/76c49ece-3edb-4ad3-8c2f-23cc67da2b0e)

![image](https://github.com/eclipse-leshan/leshan/assets/50736807/07f03240-847c-4d68-9e4e-70d0ffab1aa1)

![image](https://github.com/eclipse-leshan/leshan/assets/50736807/a7df56b3-37fb-42b5-bca9-ae65114990e3)

**Comment by sbernard31** [comment]
Hi,

It seems you are beginner with maven environment. 

> mvn install kept failing due to leshan test, so I commented out the test part in pom.xml and did mvn install.

Right way to skip test is : `mvn clean install -DskipTests`

> The mvn install was successful, and a target folder was created in each folder such as bs, client, and server, and a .jar file was created.

This is the expected behavior : creating 1 .jar file for each maven module 

> However, there is no java package, perhaps because java is not compiled.

What are you calling java package ? :thinking: 

> Is it because the leshan test was commented out in pom.xml?

No, Skipping tests should not change anything built artifacts. 

> Images related to the issue are attached below.

Please when you share textual information, to not share image ...
 - Text can be copy/paste ...
 - Text is indexed by search engine or github  ...
 - Text is much smaller than image ...

**Comment by sbernard31** [comment]
> Images related to the issue are attached below.

Please when you share textual information, to not share image ...
 - Text can be copy/paste ...
 - Text is indexed by search engine or github  ...
 - Text is much smaller than image ...
