### ISSUE TITLE
I wanna get the whole logs of SenML JSON

### ISSUE THREAD

**Issue by huny0501** [eclipse-leshan/leshan#1519]
### Question

Hello, I am using leshan server demo.

I wanna save the whole logs of SenML JSON.

But, I can see small part of SenML Logs, As follows

```
ACK-2.05   MID=47482, Token=0CDC5F06A1BD4A12, OptionSet={"Content-Format":"application/senml+json"},
 "[{"bn":"/3/0/","n":"0","vs":"Les".. 405 bytes
ACK-2.05   MID=47483, Token=10C5614C176080C1, OptionSet={"Content-Format":"application/senml+json"},
 "[{"bn":"/4/0/","n":"9","v":6},{"".. 85 bytes
```

As you know, I wanna see whole SenML JSON.

Is it possible?

If it is possible, How can I do it?

I will wait your reply :)

**Comment by sbernard31** [comment]
Where/how do you get that logs ?

**Comment by sbernard31** [comment]
I asked because I can not see which class/line raised that log but I guess you tried to log a Californium `CoapResponse`/`Response` :thinking: 

Looking at Californium code : 
https://github.com/eclipse-californium/californium/blob/507d75c5442253f7a8706401bde5d1c88e134505/californium-core/src/main/java/org/eclipse/californium/core/coap/Response.java#L153-L155

https://github.com/eclipse-californium/californium/blob/507d75c5442253f7a8706401bde5d1c88e134505/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L259-L278

https://github.com/eclipse-californium/californium/blob/507d75c5442253f7a8706401bde5d1c88e134505/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L641-L643

https://github.com/eclipse-californium/californium/blob/507d75c5442253f7a8706401bde5d1c88e134505/element-connector/src/main/java/org/eclipse/californium/elements/util/StringUtil.java#L601-L643

You could see that only 32 first character used to generated default ToString() used by LOG.  
I'm not sure you can change this by configuration.

Is it a LOG generate by your code OR a LOG generated by Leshan/Californium ? 

If this an issue for you maybe you can ask a solution at Californium repository ?

**Comment by huny0501** [comment]
I am sorry. I forgot to write class name
I will ask californium repository.
Thank you for your kind :)

**Comment by sbernard31** [comment]
(corresponding callifornium issue at https://github.com/eclipse-californium/californium/issues/2189)

**Comment by huny0501** [comment]
I am sorry, I think I dont use above classes of californium.

I am using this code.

import org.eclipse.leshan.core.response.ReadResponse;
ReadResponse readResponse = lwm2mServer.send(registration, readObject, timeout);
System.out.println(readResponse.getCoapResponse().toString());

I am recieving following log
>ACK-2.05   MID=47482, Token=0CDC5F06A1BD4A12, OptionSet={"Content-Format":"application/senml+json"},
 "[{"bn":"/3/0/","n":"0","vs":"Les".. 405 bytes
ACK-2.05   MID=47483, Token=10C5614C176080C1, OptionSet={"Content-Format":"application/senml+json"},
 "[{"bn":"/4/0/","n":"9","v":6},{"".. 85 bytes

**Comment by huny0501** [comment]
I checked again, i guess my app use classes of californium.
I will check more. Thanks!
