### ISSUE TITLE
error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by Bradymu** [eclipse-leshan/leshan#1564]
### Question

HI
There is something wrong with the handshake of the certificate. pls help to check.
1. we generate our own client/CA key and cert, after that we use CA to generate server cert, then convert to hex fill into Leshan bootstrap server sandbox.
our file:
[key_cert.zip](https://github.com/eclipse-leshan/leshan/files/13669582/key_cert.zip)

my endpoint name is rw001
we used client connect to Leshan server, but handshake failed.
Wireshark pack:
[tcpdump.zip](https://github.com/eclipse-leshan/leshan/files/13669606/tcpdump.zip)

![image](https://github.com/eclipse-leshan/leshan/assets/151825674/54be364b-ceb4-4a6c-8714-dcb73417f9e9)
 
failed log:
B0CF0A8F7F000000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../openssl-3.0.9/ssl/statem/statem_clnt.c:1889:
B0CF0A8F7F000000:error:0A000197:SSL routines:SSL_shutdown:shutdown while in init:../openssl-3.0.9/ssl/ssl✘
B0CF0A8F7F000000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../openssl-3.0.9/ssl/statem/statem_clnt.c:1889:

2. we must use Leshan server default cert? if we must use it, which CA we need to use, how to get the CA？
3. how to get the Leshan default CSR for CA to get the cert？

thanks!

BRS

**Comment by sbernard31** [comment]
> we must use Leshan server default cert? 

No, you can use a different certchain than the default one. 

> if we must use it, which CA we need to use, how to get the CA？

This is optional to use the default cert, but if you use it there is no CA as this is a self-signed certificate. In this case client must use **domain-issued certificate** usage. See different certificate usage : https://tools.ietf.org/html/rfc6698#section-2.1.1
   
> how to get the Leshan default CSR for CA to get the cert？

I don't get this question.

**Comment by Bradymu** [comment]
Hi simon
1.We decided to use the default cert for connect
    we just only generate client key and self-signed cert, no need CA key and cert?
    

2.for the "how to get the Leshan default CSR for CA to get the cert？"
What I mean is that I want to use SERVER CSR to generate CA certificates for server use, I generate CA key and cert local. 

3.why Leshan server add client info of x509 need client cert and private key, I thought this was exchanged over DTLS

BRS

**Comment by sbernard31** [comment]
> 1.We decided to use the default cert for connect
> we just only generate client key and self-signed cert, no need CA key and cert?

if you keep default server certchain (composed of only 1 certificate). There is no Certificate Authority involved because this is just a single self-signed certificate.

> 2.for the "how to get the Leshan default CSR for CA to get the cert？"
What I mean is that I want to use SERVER CSR to generate CA certificates for server use, I generate CA key and cert local.

I still don't get the question. maybe the answer of your question is at https://github.com/eclipse-leshan/leshan/wiki/Credential-files-format#x509---scroll 

> 3.why Leshan server add client info of x509 need client cert and private key

Leshan Server doesn't need you provide client cert OR/AND private key.

Maybe you are talking about Leshan Bootstrap Server ? if yes, it doesn't need it for authentication/DTLS handshake. It is needed (eventually) to write the device configuration.  In other world, this is about writing a new private / certificate on the device. (so of course it need to know what to write) 

There is a mode to change client private/cert where the bootstrap server doesn't know the private key called EST but not implemented in Leshan. See : https://github.com/eclipse-leshan/leshan/issues/1135

> , I thought this was exchanged over DTLS

Only certificates chain is exchanged during handshake. 

> 4.Have you encountered this exception before？B0CF0A8F7F000000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed

This seems to be about opensll not being able to verify certificate/certchain so that just means that what provide the server does not match what expect the client. (This could be explain by lot of different reasons)

**Comment by Bradymu** [comment]
Hi Simon,
we follow the step to get a new certain(no default). still failed and test step below:
1. we generate client key cert (c_keys.) and CA root key cert. 
2. we generate server key(s_keys) and use CA cert generate sever cert.
3. add client into leshan bootstrap server and config the X509 info.
4. running lwm2m.but failed in openssl "tls_post_process_server_certificate:certificate verify failed"
the openssl function response X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN, but the cert we generate by CAroot.are there anything wrong with me?
could you pls help use this key try using in client connect server sandbox?
we add endpoint name rw001.

thanks!
BRS

**Comment by sbernard31** [comment]
Some advice. 

1) You should read : 
 -  https://tools.ietf.org/html/rfc6698#section-2.1.1
 -  And you should also read this limitations of LWM2M 1.1 (and so Leshan for now) : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502
 
 2) You should know which kind of  "certificate usage", you are using or you want to use. 
 
 3) You should test first your certificates with **leshan-client-demo** and **leshan-server-demo** without using bootstrap. 
 
HTH
