### ISSUE TITLE
read object payload failed.

### ISSUE THREAD

**Issue by Bradymu** [eclipse-leshan/leshan#1565]
### Version(s)

leshan 2.0 

### Which components

Leshan server sandbox

### What happened

server output : 
endpoint name urn:imei:001027009999999

### How to reproduce

Hi,
read object 16/x/0/1 16/x/0/2 16/x/0/3 parse payload failed. only 16/x/0/0 read ok.
server output:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/d1900e5c-6ddb-483b-a66b-b301dda64d96)

![image](https://github.com/eclipse-leshan/leshan/assets/151825674/e8c5bac3-a57e-41a3-8f8d-574457a7001d)

we capture our client log CoAP output of 16/x/0/0 and 16/x/0/1 

it is same style between read object ok and failed:

read 16/1/0/0 ok:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/4aacccb7-ecc2-4907-ad80-492235f76dd3)

read16/1/0/1 failed:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/cd28e172-c97b-41bb-8798-85a893178d46)

Wireshark log:
[tcpdump-obj16 -readfailed.zip](https://github.com/eclipse-leshan/leshan/files/13701163/tcpdump-obj16.-readfailed.zip)

the coap packet is ok, but server parse payload failed.

pls help to check. thanks!

BRS

**Comment by sbernard31** [comment]
Some advises : 

1. In your web browser dev tool console you should see more detailed log.
2. If this is not enough, you can run server locally (in verbose mode `-v` or `-vv`or `-vvv`), try to reproduce and see you see log about that. 
3. When you provide a wireshark capture, please provide only useful packet ...
4. Stop to send screenshot to share textual information. This is fat and can not be indexed or copy/pasted ... 

Before to open a bug : 
  - Try to check if you face this issue with **leshan-client-demo** ? if not, maybe this is a hint that the bug is rather in your code and you need to investigate more before to open a bug. You can try to compare what produce **leshan-client-demo** and what produce your client. 
  - If you think this is a bug in our code, check specification/RFC and explain clearly what you think doesn't follow specification/RFC.

**Comment by Bradymu** [comment]
Hi Simon,
We test use Leshan sandbox, do you mean we can get the sandbox log of Leshan server, could you pls help to point out how to get the dev tool to get the log.

for the locally server, we still building it, but failed because Internal network, The module cannot be accessed externally. Could you give some tip for server running into the Internal network.

for the Wireshark:
server  parse ok:
11	2023-12-18 08:09:15.112008	10.98.246.233	23.97.187.154	CoAP	67	ACK, MID:58346, 2.05 Content, TKN:a0 73 1c 48 ab 86 75 bb, /16/1/0/0

server parse payload failed:
29	2023-12-18 08:10:18.780404	10.98.246.233	23.97.187.154	CoAP	67	ACK, MID:58347, 2.05 Content, TKN:00 2a 9e e8 5b 6d 37 38, /16/1/0/1

![image](https://github.com/eclipse-leshan/leshan/assets/151825674/ba36b2b3-da8a-4efd-aa5d-7817d82e9dfb)
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/4cde3ec0-402e-42c6-a1f3-fde88f8e3826)
