### ISSUE TITLE
No consistent value ordering for composite requests 

### ISSUE THREAD

**Issue by sag-eweingaertner** [eclipse-leshan/leshan#1592]
### Version(s)

all

### Which components

leshan core

### Tested With

Leshan demo client / our internal client

### What happened

**Situation**

We've discovered an **edge case**  problem in the way how Eclipse Leshan implements the values for composite operations, most notably composite writes.

First of all, let's take a precise look at the [LWM2M 1.1 spec](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.pdf#83) to table 7.4.5 on page 83: We see that the SenML-JSON here uses an Array. Arrays are an  ordered data structure. It would be fantastic if we had a chance to control the orders in the resulting SENML-JSON / CBOR.

**Why it currently does not work**

To create a WriteCompositeRequest in Leshan, the values are passed as a general map (which is unordered):
```
 public WriteCompositeRequest(ContentFormat contentFormat, Map<String, Object> values) {
```

Internally, Leshan then takes the value map (which theoretically could have an order, for example if one uses a SortedMap or similar) and pushes the map entries to a HashMap. At this time, any order would be lost. In effect, there  is no way to define the order

**Why this is a only a smaller problem**

Arguably, any client that expects entries to have a certain order in SenML-JSON is a poor implementation.
See LWM2M spec section 6.3.9: 

> The "Write-Composite" operation is atomic and cannot have partial success. That is, if the client supports this
operation, it MUST reject a Server request where it cannot successfully write all the requested values to the requested
list of Resources. Therefore, before processing Write-Composite, the client MUST ensure that all addressed objects exist
and that the Server has write access to those Objects and Resources

Still, to be on the safe side, it would be fantastic if there was a way to control the order...

### How to reproduce

Create a WriteComposite operation and observe the order of values in SenML

**Comment by sbernard31** [comment]
Could you explain a bit more why order is important ? 

I get that this is about client implementation but I'm curious to better understand this "client bug" ? :thinking:

**Comment by JPSELC** [comment]
@sbernard31 We are seeing this issue in an override sequence which goes something like
1. Set Override timer
2. Turn Light On
3. Set Light Brightness.

It's a sequence where 2 is dependent on 1 and 3 is dependent on 2.
We can of course do this in 3 separate writes, waiting for the acknowledges etc, but if we could do this with an ordered compound write, it would simplify it and be far faster, especially in a slow network.
Obviously we can add custom code which handles a compound write with these 3 attributes and executes them in the correct order, but in general it would be better if we could rely on the order of the commands in the compound write.

The issue really is that the LwM2M Spec doesn't indicate that the order of the writes is respected.

**Comment by sbernard31** [comment]
> It's a sequence where 2 is dependent on 1 and 3 is dependent on 2.

I'm not sure to get what means _"override timer"_  
But for _"turn light on"_ and _"set light brightness"_, I'm not sure to see why order should be critical. :thinking:   

At first sight, that's really looks like client implementation issue. (Maybe a good idea to try to also fix client at mid/long term ?)

> The issue really is that the LwM2M Spec doesn't indicate that the order of the writes is respected.

Maybe I missed something but I can not see why this would be a specification issue. 

Currently, I think is not wrong to state that **Write Composite** Operation should be considered as atomic.
It  makes sense with **Write Composite** using [**CoAP** `iPatch`](https://www.rfc-editor.org/rfc/rfc8132.html#section-1.2) which is idempotent. 

Not sure, but I guess your client should not like too much that you execute those `WriteCompositeRequest` twice if order is important ? (so not really idempotent) 

> Obviously we can add custom code which handles a compound write with these 3 attributes and executes them in the correct order, but in general it would be better if we could rely on the order of the commands in the compound write.

Generally, I prefer letting user being able to provide custom code for their out of spec use case. (see [Real Life is about dealing with non-compliant foreign peer behavior.](https://github.com/eclipse-leshan/leshan/wiki/How-Leshan-should-behave-with-Non-Compliant-Implementations-%3F#real-life-is-about-dealing-with-non-compliant-foreign-peer-behavior))

But here a solution could be that we use [`LinkedHashMap` ](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html) instead of `HashMap` in `WriteCompositeRequest`.
This would at cost  of  2 additional object reference by maps entry : 2 x 32 bits or 64 bits (depends of JVM)  by entry.
This would only keep order in `WriteCompositeRequest` then no guarantee that decoder/encoder will respect it. 

If we don't want to pay that cost, another solution would be to provide, a protected constructor in `WriteCompositeRequest` which allow you to create a `OrderedWriteCompositeRequest` using whatever map you want internally. 

Oh I also just see that if you use this constructor : `WriteCompositeRequest.WriteCompositeRequest(ContentFormat, Map<LwM2mPath, LwM2mNode>, Object)` order should be respected. (If I read the code correctly)

Let me know your opinion about that :pray: 

> We can of course do this in 3 separate writes, waiting for the acknowledges etc, but if we could do this with an ordered compound write, it would simplify it and be far faster, especially in a slow network.

Do you have numbers about how this will really impact in real world. 
Keep free to give real numbers because in call cases (even if number seems very low) we will try to find a solution for you use case. 
I just try to have a better vision of real world.

**Comment by JPSELC** [comment]
Re: Maybe I missed something but I can not see why this would be a specification issue.
My point here is that because there is no mention of order of compound writes being respected in the spec, there is no onus on anyone to implement it that way, so in general one could not rely on that.
The fact that compound commands are atomic is great, and I guess that's the whole point of compound commands, but I think it would be more powerful if the order of commands was respected too.

As regards numbers on timing, Cat-NB has a maximum latency of 10 seconds, so sending 3 commands and waiting for acknowledges would take up to 60 seconds, versus 20 seconds, which might not seem a lot, but it becomes important when there is scale involved.

Regarding running the commands twice, that might work, but it might take 3 times to satisfy the dependencies.

Thanks for your consideration. I think we have the answers we need.

**Comment by sbernard31** [comment]
> As regards numbers on timing, Cat-NB has a maximum latency of 10 seconds, so sending 3 commands and waiting for acknowledges would take up to 60 seconds, versus 20 seconds, which might not seem a lot, but it becomes important when there is scale involved.

Thx that's really help me to better understand this kind of use case. 

> Regarding running the commands twice, that might work, but it might take 3 times to satisfy the dependencies.

An [idempotent function](https://en.wikipedia.org/wiki/Idempotence) should have same result if it is applied 1 or several time.
In that case, if you send it 1 or 2 times, the state of the client should be the same. 
So, Regarding your answer, I understand the implementation is not idempotent.

(But I agree, this is very theoretically and I can understand that some implementation doesn't full respect that)

> Thanks for your consideration. I think we have the answers we need.

That means that using `WriteCompositeRequest.WriteCompositeRequest(ContentFormat, Map<LwM2mPath, LwM2mNode>, Object)`  works for you ? 

If yes, let me know. 
If you think this would be better to introduce `LinkedHashMap` for the other constructor let me know too.

I wait for you confirmation before to close the issue.

Thx for taking time to share your issue, all feedback are welcome.

**Comment by JPSELC** [comment]
Thanks Simon. I think we can close the issue. 
We need to work with the situation where the order is not determinate.

**Comment by sbernard31** [comment]
You're welcome. :slightly_smiling_face: 

Do not hesitate to reopen if needed.
