### ISSUE TITLE
How to know if a cliente Lwm2m 1.0 is availble

### ISSUE THREAD

**Issue by mathns2803** [eclipse-leshan/leshan#1593]
### Question

I have a cliente Lwm2m 1.0. It is connected in a server, but sometimes, When I request a reading or a observer I do not have any response because the client disconnected without deregister.
I know that I have a gap to request and get my response, so my question is, "How can I know if the client is connected or not?"

**Comment by sbernard31** [comment]
Currently Leshan only support `coap` and `coaps` protocol both are based on UDP. Unlike TCP, there is no connected/disconnected state manage at OS level. So it should be done at application level. 

**At LWM2M level**, by default, a registered client is supposed to be always reachable. 

 - A client send **Register** request to say : I"m here and I will tell you "I'm alive"  before `lifetime` seconds. (`lifetime` value is sent in Register request)
- Then it send periodically **Update** Registration Request to say : I'm still alive.  (if server don't get the **Update** in time,  registration is deleted)
- When client "disconnect",  it should send  **De-Register** to say : I"m not here anymore. (server deletes registration)

In LWM2M, there is also a Queue Mode (very bad name) which is used by clients which are not always reachable.
In that case there are only available view seconds/minutes after a **Register** or **Update** Request. The rest of the time client is sleeping OR not reachable because of network (e.g. behind a NAT). In that case **Leshan** server, try to guess when the device is present and you get the information with `LeshanServer.getPresenceService()`.  (but again this is only for Queue Mode)
(more details in [LWM2M specifications](https://github.com/eclipse-leshan/leshan/wiki/Lightweight-M2M-Specification))

So if any of the mechanism is used correctly by client, the only way to know is to send a request and wait for Timeout...

**At DTLS level** (so when using `coaps`), there is a kind of connection. Client can send a [`CLOSE NOTIFY` ](https://www.rfc-editor.org/rfc/rfc5246#section-7.2.1) message to close the DTLS connection. DTLS connection has no impact on LWM2M registration BUT if there is no DTLS Connection when server try to send a request, there is 2 possible behavior : 
- by default, server will try to initiate a DTLS Handshake to the client, if that fail (after several seconds/minutes) : you will get a timeout
-  if server is configured as server only, server will immediately raise an `UnconnectedPeerException`.

HTH

**Comment by mathns2803** [comment]
About this point "**if server don't get the Update in time, registration is deleted**"

Can I configure this 'timeout', or It's defined on the client?

**Comment by mathns2803** [comment]
I see, It works for me, thanks for everything!!

**Comment by sbernard31** [comment]
You're welcome :slightly_smiling_face: 

(I guess we can close the issue)
