### ISSUE TITLE
Add new object

### ISSUE THREAD

**Issue by Pmctst** [eclipse-leshan/leshan#1606]
### Question

My application contains a String. It is a string about 265 characters max.
I have checked Open Mobile documentation related to objects (https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html) and I have seen that 5527 object is a String of text. This would be perfect for me.

I tried to create in the Leshan demo server but it does not appear on the web. If I create a temperature object I see there. Is it because it is not an OMA object? Is is possible to include new objects on the demo server?

I tried creating it with the demo client and the response is: Unable to enable Object 5527 : there no model for this object.

How can I include a new model?

**Comment by sbernard31** [comment]
I guess your are talking about reusable resource 5527.

| ResourceID | Name/Technical Spec |	Operation |	Type | 	Range/Enumeration |	Units | Submitter | Description |
|- | - | - | - | - | - | - | - |
|5527 ||Text| RW | String |	| IPSO |A string of text. |

For now there is no support of reusable resource : https://github.com/eclipse-leshan/leshan/issues/329

We are not sure this is really useful as in real use case, you need the whole model anyway. See https://github.com/eclipse-leshan/leshan/wiki/Adding-new-objects

> I tried to create in the Leshan demo server but it does not appear on the web. If I create a temperature object I see there. Is it because it is not an OMA object? 
> I tried creating it with the demo client and the response is: Unable to enable Object 5527 : there no model for this object.

I'm confused now because it seems you talk about an object with the ID 5527 but I thought that you talk about a reusable resource :confused: 

I let you read links I shared and maybe if you still don't get your answer you could try to reformulate ?


> Is is possible to include new objects on the demo server?
> How can I include a new model?

See :
- https://github.com/eclipse-leshan/leshan/wiki/Adding-new-objects#leshan-server-demo
- https://github.com/eclipse-leshan/leshan/wiki/Adding-new-objects#leshan-client-demo

**Comment by Pmctst** [comment]
Thank you @sbernard31 
I will read your links carefully and I will ask again in case I need. If I have everything clear, I will close this question.

What I need is the possibility to include 5527 object support in the server so I can use it with my client device.
Or, in case I create a new object with the values I want, how can I include its support on the demo server?

**Comment by Pmctst** [comment]
I close the issue. I found what I needed on the webpages provided. Thank you!
