### ISSUE TITLE
update from `@CycloneDX/cyclonedx-node-yarn` project

### ISSUE THREAD

**Issue by jkowalleck** [eclipse-leshan/leshan#1632]
### Question

see https://github.com/eclipse-leshan/leshan/blob/2a1a8af1f6a7393fdd66f0d7ca3a10edd8bdc1f3/.jenkins/weekly.jenkins#L43-L45

Just wanted to let you know, that the `@CycloneDX/cyclonedx-node-yarn` project was backed, and is actively maintained for a while, now.
Please let us know if you find any issues :D

**Comment by sbernard31** [comment]
@jkowalleck thx for letting me know that :pray: 

I decided to test it some weeks ago but I was stopped quickly because `cyclonedx-node-yarn` does not support yarn 1.x. ( >v3 is required). I understand that you maybe don't want  to target a so old version of yarn. (so I didn't provide you any feedback about that)

On our side, this is maybe not so easy to migrate from yarn classic (v1) to modern yarn (v3 or v4) : https://github.com/eclipse-leshan/leshan/issues/1550

**Comment by sbernard31** [comment]
As we already have an issue (https://github.com/eclipse-leshan/leshan/issues/1550) to track that, so I think we can close this. 
For completeness I added a comment to that issue : https://github.com/eclipse-leshan/leshan/issues/1550#issuecomment-2286362731
